### ISSUE TITLE
Deprecated dependencies

### ISSUE THREAD

**Issue by ckousik** [taskcluster/docker-exec-websocket-server#5]
I'm planning to use this package as a part of my gsoc project but a lot of packages are deprecated or are not fixed to a specific version.

**Comment by jonasfj** [comment]
Using versions like `"^2.1.3"` is very sane... deprecated packages are not ideal... but hey could be worse :)

Feel free to get this running with newer versions and submit a PR... I think we need node 4 (maybe even node `0.12` compatibility).

Note: the tests are a bit hard to run...I think you have need to have docker running locally or something.

**Comment by ckousik** [comment]
It was very hard but I did get it to run. ES6ifying this is also an issue.

**Comment by jwhitlock** [comment]
Closing this 2016 issue. Feel free to re-open, or re-test with the current code base.
